name: FastAdmin Addon Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP 7.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run addon command
      run: |
        php think addon -a qurexam -c move
        php think addon -a qurexam -c package
